# Generated by Django 5.2.8 on 2025-11-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='location',
            field=models.TextField(default='Default Location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='target',
            field=models.CharField(default='Default Location', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='working_hours',
            field=models.CharField(default='Default Location', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='branch',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
