# Generated by Django 5.2.8 on 2025-11-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('name_uz', models.CharField(max_length=64, null=True)),
                ('name_en', models.CharField(max_length=64, null=True)),
            ],
            options={
                'verbose_name': 'city',
                'verbose_name_plural': 'cities',
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True, unique=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('language_code', models.CharField(choices=[('en', 'English'), ('uz', "O'zbekcha"), ('ru', 'Русский')], default='en', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'telegram_users',
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='location_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='location_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='target_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='target_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='title_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='title_uz',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='categories',
            name='title_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='categories',
            name='title_uz',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_uz',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
